<?php

use RA\Modules;

$modules = Modules::singleton();

$modules->add_module(' Standard Portfolio', 'standard-portfolio', 'page_modules', [
	array(
        'key' => 'field_5er4559255f482s',
        'label' => 'Section Title',
        'name' => 'sec_title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ),
    array(
        'key' => 'field_5ees56f6d5deec5',
        'label' => 'Title Alignment',
        'name' => 'title_alignment',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'left' => 'Left',
            'center' => 'Center',
            'right' => 'Right',
        ),
        'default_value' => array(
            0 => 'Left',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_5ees56f6d5deec56',
        'label' => 'Enable Filter',
        'name' => 'enable_filter',
        'type' => 'select',
        'instructions' => 'Only items in the View All category will be displayed if filtering is disabled.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'no' => 'No',
            'yes' => 'Yes',
        ),
        'default_value' => array(
            0 => 'No',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_5ees56f6d5deec57',
        'label' => 'Description on Hover',
        'name' => 'enable_hover',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'no' => 'No',
            'yes' => 'Yes',
        ),
        'default_value' => array(
            0 => 'No',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_5ees56f6d5deec58',
        'label' => 'Section Background',
        'name' => 'bg_color',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'bg-default' => 'Default',
            'bg-light' => 'Light',
            'bg-dark' => 'Dark',
        ),
        'default_value' => array(
            0 => 'Default',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
    ),
    array(
        'key' => 'field_5cddb7bs6581erf',
        'label' => 'Portfolio Items',
        'name' => 'items',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'collapsed' => '',
        'min' => 1,
        'max' => 0,
        'layout' => 'block',
        'button_label' => 'Add New Item',
        'sub_fields' => array(
			array(
				'key' => 'field_s5c915501a523o3',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
                'key' => 'fielder4sfa6c5746ffrt',
                'label' => 'Image Type',
                'name' => 'img_type',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'img_normal' => 'Normal',
                    'img_logo_light' => 'Logo Light',
                    'img_logo_dark' => 'Logo Dark',
                ),
                'default_value' => array(
                    0 => 'Logo Dark',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
			 array(
				'key' => 'field_s5c9257e6134rf',
				'label' => 'Heading',
				'name' => 'heading',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_5cf5s6b4ererttf',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			 array(
				'key' => 'field_s5c9257e4134rf',
				'label' => 'Category Name',
				'name' => 'category_name',
				'type' => 'text',
				'instructions' => 'Relevant if filtering is enabled.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_s5c925ee35ff',
				'label' => 'Hide from View All Tab',
				'name' => 'grouped_item',
				'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'no' => 'No',
                    'yes' => 'Yes',
                ),
                'default_value' => array(
                    0 => 'No',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
			array(
				'key' => 'field_s5c592ee6134rf',
				'label' => 'Company Position',
				'name' => 'company_position',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
			),
			array(
				'key' => 'field_5ees56f6d5deec4',
				'label' => 'Link Targeted Page or Post',
				'name' => 'link_post',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'post',
					1 => 'page',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
			array(
				'key' => 'fielsd_5c9275e3334rf',
				'label' => 'Web Link',
				'name' => 'web_link',
				'type' => 'text',
				'instructions' => 'This field will override post/page URL',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
			),
		),
	),
]);
